### ISSUE TITLE
[QUESTION] Build names and allowed characters

### ISSUE THREAD

**Issue by JayDee696969** [drinfernoo/plugin.program.aftermath#138]
Question, trying to track down a random issue im having. Its temperamental and doesnt happen all the time. Somethings causing the wizard not to open and throws an error. I can fix this by going to the wizard settings and clicking defaults under the Build Options category. In some build titles in my build.txt I am using the (-) key in the title of the build, for example name="My Build  -Debrid ONLY-"   Do you think the (-) character could be causing the error? I was able to duplicate the error others were getting and pulled the log, this is the error. Please let me know if you have any insight or clue from this error please, thank you!!
2021-07-25 23:03:39.844 T:17169   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'bool' and 'str'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.wizard/default.py", line 29, in <module>
                                                       dispatcher.dispatch(_handle, _params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.wizard/resources/libs/common/router.py", line 52, in dispatch
                                                       MainMenu().get_listing()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.wizard/resources/libs/gui/main_menu.py", line 58, in get_listing
                                                       if version > CONFIG.BUILDVERSION:
                                                   TypeError: '>' not supported between instances of 'bool' and 'str'
                                                   -->End of Python script error report<--``

**Comment by SerpentDrago** [comment]
Post your  builds txt and uservar.

**Comment by JayDee696969** [comment]
> Post your builds txt and uservar.

[uservar.zip](https://github.com/a4k-openproject/plugin.program.openwizard/files/6885613/uservar.zip)

**Comment by JayDee696969** [comment]
Full wizard here: 
[plugin.program.chef19.zip](https://github.com/a4k-openproject/plugin.program.openwizard/files/6887732/plugin.program.chef19.zip)

**Comment by JayDee696969** [comment]
Any idea?
